### ISSUE TITLE
Not able to build with Java 18

### ISSUE THREAD

**Issue by dalelane** [SolaceLabs/event-discovery-agent#9]
I know the README says Java 11 is a requirement, but I was hoping that the intent is Java 11+ rather than a hard requirement on 11.

But please feel free to close this if Java 11 is intended to be a hard requirement.

```
[ERROR] class org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite cannot access a member 
of class java.util.Collections$UnmodifiableCollection (in module java.base) with modifiers "public"
```

[build.log](https://github.com/SolaceLabs/event-discovery-agent/files/9896875/build.log)

**Comment by Mrc0113** [comment]
Hey @dalelane. I don't think it was initially  meant to be a hard requirement but with this bug maybe it is for now. Thanks for opening but I'm going to close this as we don't plan on enhancing the project to support java 18 at this time. That said, if you already fixed it and want to make a PR we'd take a look at it.
